export enum RepetitionReminderSkipReason {
  REMINDER_NOT_FOUND = 'REMINDER_NOT_FOUND',
  REMINDER_ALREADY_SENT = 'REMINDER_ALREADY_SENT',
  REMINDER_CANCELED = 'REMINDER_CANCELED',
  LEAD_WITHOUT_ACCOUNT = 'LEAD_WITHOUT_ACCOUNT',
  LEAD_WITHOUT_LANGUAGE = 'LEAD_WITHOUT_LANGUAGE',
  LEAD_LABEL_CHANGED = 'LEAD_LABEL_CHANGED',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
}

export const REPETITION_REMINDER_ROUTING_KEY = 'lead.repetition.reminder';
export const REPETITION_REMINDER_BUSINESS_WINDOW_PREFIX =
  'REPETITION_REMINDER';
