services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fenix_api
    restart: unless-stopped

    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      YCLOUD_API_KEY: ${YCLOUD_API_KEY}

    # Permite acceder al Postgres del host en Ubuntu
    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - nginx-proxy-manager-zr1y_default

networks:
  nginx-proxy-manager-zr1y_default:
    external: true