export enum LabelMessageRuleSkipReason {
  RULE_NOT_FOUND = 'RULE_NOT_FOUND',
  RULE_INACTIVE = 'RULE_INACTIVE',
  ASSIGNMENT_NOT_FOUND = 'ASSIGNMENT_NOT_FOUND',
  LEAD_LABEL_CHANGED = 'LEAD_LABEL_CHANGED',
  LEAD_WITHOUT_ACCOUNT = 'LEAD_WITHOUT_ACCOUNT',
  LEAD_WITHOUT_LANGUAGE = 'LEAD_WITHOUT_LANGUAGE',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_NOT_APPROVED = 'TEMPLATE_NOT_APPROVED',
}

export const LABEL_MESSAGE_RULE_ROUTING_KEY = 'lead.label.message.rule';
export const LABEL_MESSAGE_RULE_BUSINESS_WINDOW_PREFIX = 'LABEL_MESSAGE_RULE';
