export enum ReengagementSkipReason {
  LEAD_WITHOUT_ACCOUNT = 'LEAD_WITHOUT_ACCOUNT',
  LEAD_WITHOUT_LANGUAGE = 'LEAD_WITHOUT_LANGUAGE',
  LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',
  LEAD_ALREADY_RESPONDED = 'LEAD_ALREADY_RESPONDED',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  CAMPAIGN_TEMPLATE_NOT_APPROVED = 'CAMPAIGN_TEMPLATE_NOT_APPROVED',
}

export const REENGAGEMENT_EXCHANGE = 'fenix.campaigns';
export const REENGAGEMENT_ROUTING_KEY = 'lead.reengagement.week1';
